[project]
name = "tthol-memory"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11.9"
dependencies = [
    "psutil>=7.2.2",
    "pymem>=1.14.0",
    "pywin32>=311",
]
